export const tags = {
  userTag: "User",
  mediaTag: "Media",
  roleTag: "Role",
  employeeTag: "employeeTag",
  productTag: "productTag",
  categoryTag: "categoryTag",
  brandTag: "brandTag",
  attributeTag: "attributeTag",
  paymentMethodTag: "paymentMethodTag",
  questionTag: "questionTag",
  couponTag: "couponTag",
  orderTag: "orderTag",
  settingsTag: "settingsTag",
  vendorProfile: "VendorProfile",
  walletTag: "walletTag",
  refundTag: "refundTag",
  pagesTag: "pagesTag",
  reportTag: "reportTag",
  paymentTag: "paymentTag",
  campaignTag: "campaignTag",
  bannerTag: "bannerTag",
  reviewTag: "reviewTag",
  shippingTag: "shippingTag",
  chatTag: "chatTag",
  notificationTag: "Notification",
  offer: "Offer",
  offerCategory: "offerCategory",
  smartLink: "smartLink",
  automation: "automation",
  conversion: "conversion",
  offerApplication: "offerApplication",
  tenant: "tenant",
  team: "team",
  billing: "billing",
  affiliate: "affiliate",
} as const;

export const tagTypes = Object.values(tags);
